In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jmmvutu/summer-products-and-sales-in-ecommerce-wish")

print("Path to dataset files:", path)

/Users/jeongho/Desktop/w25536-kaggle/kaggle/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.4)
Path to dataset files: /Users/jeongho/.cache/kagglehub/datasets/jmmvutu/summer-products-and-sales-in-ecommerce-wish/versions/5

In [3]:
path

'/Users/jeongho/.cache/kagglehub/datasets/jmmvutu/summer-products-and-sales-in-ecommerce-wish/versions/5'

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import os

df = pd.read_csv(
    os.path.join(path, "summer-products-with-rating-and-performance_2020-08.csv")
)

In [6]:
df

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,EUR,10000,1,4.08,1367,722.0,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,EUR,100,1,3.07,28,11.0,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,EUR,100,0,3.71,59,24.0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,2.50,2,0.0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,4.07,14,8.0,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 528.6+ KB

In [8]:
df.isnull().sum()

title                              0
title_orig                         0
price                              0
retail_price                       0
currency_buyer                     0
units_sold                         0
uses_ad_boosts                     0
rating                             0
rating_count                       0
rating_five_count                 45
rating_four_count                 45
rating_three_count                45
rating_two_count                  45
rating_one_count                  45
badges_count                       0
badge_local_product                0
badge_product_quality              0
badge_fast_shipping                0
tags                               0
product_color                     41
product_variation_size_id         14
product_variation_inventory        0
shipping_option_name               0
shipping_option_price              0
shipping_is_express                0
countries_shipped_to               0
inventory_total                    0
has_urgency_banner              1100
urgency_text                    1100
origin_country                    17
merchant_title                     0
merchant_name                      4
merchant_info_subtitle             1
merchant_rating_count              0
merchant_rating                    0
merchant_id                        0
merchant_has_profile_picture       0
merchant_profile_picture        1347
product_url                        0
product_picture                    0
product_id                         0
theme                              0
crawl_month                        0
dtype: int64

In [9]:
print(df.columns)

Index(['title', 'title_orig', 'price', 'retail_price', 'currency_buyer',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='object')

In [10]:
columns_to_drop = [
    "title",
    "title_orig",
    "currency_buyer",
    "shipping_option_name",
    "urgency_text",
    "merchant_title",
    "merchant_name",
    "merchant_info_subtitle",
    "merchant_id",
    "merchant_profile_picture",
    "product_url",
    "product_picture",
    "product_id",
    "tags",
    "has_urgency_banner",
    "theme",
    "crawl_month",
    "origin_country",
]

In [11]:
df.drop(columns_to_drop, axis=1, inplace=True)

In [12]:
df

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,product_color,product_variation_size_id,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,merchant_rating_count,merchant_rating,merchant_has_profile_picture
0,16.00,14,100,0,3.76,54,26.0,8.0,10.0,1.0,...,white,M,50,4,0,34,50,568,4.128521,0
1,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,...,green,XS,50,2,0,41,50,17752,3.899673,0
2,8.00,43,100,0,3.57,14,5.0,4.0,2.0,0.0,...,leopardprint,XS,1,3,0,36,50,295,3.989831,0
3,8.00,8,5000,1,4.03,579,295.0,119.0,87.0,42.0,...,black,M,50,2,0,41,50,23832,4.020435,0
4,2.72,3,100,1,3.10,20,6.0,4.0,2.0,2.0,...,yellow,S,1,1,0,35,50,14482,4.001588,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,6.00,9,10000,1,4.08,1367,722.0,293.0,185.0,77.0,...,navyblue,S,50,2,0,41,50,5316,4.224605,0
1569,2.00,56,100,1,3.07,28,11.0,3.0,1.0,3.0,...,lightblue,S,2,1,0,26,50,4435,3.696054,0
1570,5.00,19,100,0,3.71,59,24.0,15.0,8.0,3.0,...,white,SIZE S,15,2,0,11,50,210,3.961905,0
1571,13.00,11,100,0,2.50,2,0.0,1.0,0.0,0.0,...,white,Size S.,36,3,0,29,50,31,3.774194,0
1572,7.00,6,100,1,4.07,14,8.0,3.0,1.0,0.0,...,red,S,50,2,0,41,50,7023,4.235939,0

In [13]:
df.isnull().sum()

price                            0
retail_price                     0
units_sold                       0
uses_ad_boosts                   0
rating                           0
rating_count                     0
rating_five_count               45
rating_four_count               45
rating_three_count              45
rating_two_count                45
rating_one_count                45
badges_count                     0
badge_local_product              0
badge_product_quality            0
badge_fast_shipping              0
product_color                   41
product_variation_size_id       14
product_variation_inventory      0
shipping_option_price            0
shipping_is_express              0
countries_shipped_to             0
inventory_total                  0
merchant_rating_count            0
merchant_rating                  0
merchant_has_profile_picture     0
dtype: int64

In [14]:
## Encoding


def ordinal_encode(data, column, orderding):
    return data[column].apply(lambda x: orderding.index(x) if x in orderding else None)

In [15]:
df["product_variation_size_id"].unique()

array(['M', 'XS', 'S', 'Size-XS', 'M.', 'XXS', 'L', 'XXL', nan, 'S.', 's',
       'choose a size', 'XS.', '32/L', 'Suit-S', 'XXXXXL', 'EU 35', '4',
       'Size S.', '1m by 3m', '3XL', 'Size S', 'XL', 'Women Size 36',
       'US 6.5 (EU 37)', 'XXXS', 'SIZE XS', '26(Waist 72cm 28inch)',
       'Size XXS', '29', '1pc', '100 cm', 'One Size', 'SIZE-4XL', '1',
       'S/M(child)', '2pcs', 'XXXL', 'S..', '30 cm', '5XL', '33',
       'Size M', '100 x 100cm(39.3 x 39.3inch)', '100pcs', '2XL', '4XL',
       'SizeL', 'SIZE XXS', 'XXXXL', 'Base & Top & Matte Top Coat',
       'size S', '35', '34', 'SIZE-XXS', 'S(bust 88cm)',
       'S (waist58-62cm)', 'S(Pink & Black)', '20pcs', 'US-S',
       'Size -XXS', 'X   L', 'White', '25', 'Size-S', 'Round',
       'Pack of 1', '1 pc.', 'S Diameter 30cm', '6XL',
       'AU plug Low quality', '5PAIRS', '25-S', 'Size/S', 'S Pink',
       'Size-5XL', 'daughter 24M', '2', 'Baby Float Boat', '10 ml', '60',
       'Size-L', 'US5.5-EU35', '10pcs', '17', 'Size-XXS', 'Women Size 37',
       '3 layered anklet', '4-5 Years', 'Size4XL', 'first  generation',
       '80 X 200 CM', 'EU39(US8)', 'L.', 'Base Coat', '36', '04-3XL',
       'pants-S', 'Floating Chair for Kid', '20PCS-10PAIRS', 'B',
       'Size--S', '5', '1 PC - XL', 'H01', '40 cm', 'SIZE S'],
      dtype=object)

In [16]:
df["product_variation_size_id"].value_counts()

product_variation_size_id
S                      641
XS                     356
M                      200
XXS                    100
L                       49
                      ...
6XL                      1
AU plug Low quality      1
XXXL                     1
25-S                     1
SIZE S                   1
Name: count, Length: 106, dtype: int64

In [17]:
size_ordering = ["XXS", "XS", "S", "M", "L", "XL", "XXL"]

In [18]:
df["product_variation_size_id"] = ordinal_encode(
    df, "product_variation_size_id", size_ordering
)

In [19]:
df

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,product_color,product_variation_size_id,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,merchant_rating_count,merchant_rating,merchant_has_profile_picture
0,16.00,14,100,0,3.76,54,26.0,8.0,10.0,1.0,...,white,3.0,50,4,0,34,50,568,4.128521,0
1,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,...,green,1.0,50,2,0,41,50,17752,3.899673,0
2,8.00,43,100,0,3.57,14,5.0,4.0,2.0,0.0,...,leopardprint,1.0,1,3,0,36,50,295,3.989831,0
3,8.00,8,5000,1,4.03,579,295.0,119.0,87.0,42.0,...,black,3.0,50,2,0,41,50,23832,4.020435,0
4,2.72,3,100,1,3.10,20,6.0,4.0,2.0,2.0,...,yellow,2.0,1,1,0,35,50,14482,4.001588,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,6.00,9,10000,1,4.08,1367,722.0,293.0,185.0,77.0,...,navyblue,2.0,50,2,0,41,50,5316,4.224605,0
1569,2.00,56,100,1,3.07,28,11.0,3.0,1.0,3.0,...,lightblue,2.0,2,1,0,26,50,4435,3.696054,0
1570,5.00,19,100,0,3.71,59,24.0,15.0,8.0,3.0,...,white,NaN,15,2,0,11,50,210,3.961905,0
1571,13.00,11,100,0,2.50,2,0.0,1.0,0.0,0.0,...,white,NaN,36,3,0,29,50,31,3.774194,0
1572,7.00,6,100,1,4.07,14,8.0,3.0,1.0,0.0,...,red,2.0,50,2,0,41,50,7023,4.235939,0

In [21]:
def onehot_encode(data, column):
    dummies = pd.get_dummies(data[column], dtype=int)
    data = pd.concat([data, dummies], axis=1)
    data.drop(column, axis=1, inplace=True)
    return data

In [22]:
df1 = onehot_encode(df, "product_color")

In [23]:
df1

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,white & black,white & green,white & red,whitefloral,whitestripe,wine,wine red,winered,winered & yellow,yellow
0,16.00,14,100,0,3.76,54,26.0,8.0,10.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1,8.00,22,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,...,0,0,0,0,0,0,0,0,0,0
2,8.00,43,100,0,3.57,14,5.0,4.0,2.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,8.00,8,5000,1,4.03,579,295.0,119.0,87.0,42.0,...,0,0,0,0,0,0,0,0,0,0
4,2.72,3,100,1,3.10,20,6.0,4.0,2.0,2.0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,6.00,9,10000,1,4.08,1367,722.0,293.0,185.0,77.0,...,0,0,0,0,0,0,0,0,0,0
1569,2.00,56,100,1,3.07,28,11.0,3.0,1.0,3.0,...,0,0,0,0,0,0,0,0,0,0
1570,5.00,19,100,0,3.71,59,24.0,15.0,8.0,3.0,...,0,0,0,0,0,0,0,0,0,0
1571,13.00,11,100,0,2.50,2,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1572,7.00,6,100,1,4.07,14,8.0,3.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
(df1.dtypes == "object").sum()

0

In [25]:
pd.set_option("display.max_rows", None)

In [28]:
df1.isnull().sum()

price                             0
retail_price                      0
units_sold                        0
uses_ad_boosts                    0
rating                            0
rating_count                      0
rating_five_count                45
rating_four_count                45
rating_three_count               45
rating_two_count                 45
rating_one_count                 45
badges_count                      0
badge_local_product               0
badge_product_quality             0
badge_fast_shipping               0
product_variation_size_id       195
product_variation_inventory       0
shipping_option_price             0
shipping_is_express               0
countries_shipped_to              0
inventory_total                   0
merchant_rating_count             0
merchant_rating                   0
merchant_has_profile_picture      0
Army green                        0
Black                             0
Blue                              0
Pink                              0
RED                               0
Rose red                          0
White                             0
applegreen                        0
apricot                           0
army                              0
army green                        0
armygreen                         0
beige                             0
black                             0
black & blue                      0
black & green                     0
black & stripe                    0
black & white                     0
black & yellow                    0
blackwhite                        0
blue                              0
blue & pink                       0
brown                             0
brown & yellow                    0
burgundy                          0
camel                             0
camouflage                        0
claret                            0
coffee                            0
coolblack                         0
coralred                          0
darkblue                          0
darkgreen                         0
denimblue                         0
dustypink                         0
floral                            0
fluorescentgreen                  0
gold                              0
gray                              0
gray & white                      0
green                             0
grey                              0
greysnakeskinprint                0
ivory                             0
jasper                            0
khaki                             0
lakeblue                          0
leopard                           0
leopardprint                      0
light green                       0
lightblue                         0
lightgray                         0
lightgreen                        0
lightgrey                         0
lightkhaki                        0
lightpink                         0
lightpurple                       0
lightred                          0
lightyellow                       0
mintgreen                         0
multicolor                        0
navy                              0
navy blue                         0
navyblue                          0
navyblue & white                  0
nude                              0
offblack                          0
offwhite                          0
orange                            0
orange & camouflage               0
orange-red                        0
pink                              0
pink & black                      0
pink & blue                       0
pink & grey                       0
pink & white                      0
prussianblue                      0
purple                            0
rainbow                           0
red                               0
red & blue                        0
rose                              0
rosegold                          0
rosered                           0
silver                            0
skyblue                           0
star                              0
tan                               0
violet                            0
watermelonred                     0
white                             0
white & black                     0
white & green                     0
white & red                       0
whitefloral                       0
whitestripe                       0
wine                              0
wine red                          0
winered                           0
winered & yellow                  0
yellow                            0
dtype: int64

In [27]:
for column in null_columns:
    df[column] = = df[column].

SyntaxError: invalid syntax (2348687492.py, line 2)